### ISSUE TITLE
f3kgrain_v0.4MOD - HBD awareness

### ISSUE THREAD

**Issue by Dogway** [kedaitinh12/AVSPlus-Plugins#1]
Replying from [here](https://forum.doom9.org/showthread.php?p=1963600#post1963600), the code seems fine but it's not HBD aware.

This line specially:
https://github.com/kedaitinh12/AVSPlus-Scripts/blob/c86ed2d4222c626a953c3794cfff625a714d8d8b/f3kgrain_v0.4MOD.avsi#L91
Change to constants like:
`Lclip.ex_lut(Format("x {adaptHBD} - abs range_max * {adaptHBD} range_half - abs range_half + /"), UV=1, fulls=true)`

Format() is just a preference, you can keep string(). adaptHBD is the `adapt` variable scaled to HBD, you need to do this always when an addition or substraction is performed with:
`adaptHBD = ex_bs(adapt, 8, bi, true)`

Also don't use old internal functions like **isYV12()**, it's not HBD aware, use **Is420()** instead.

**Comment by kedaitinh12** [comment]
Thanks

**Comment by kedaitinh12** [comment]
done https://github.com/kedaitinh12/AVSPlus-Scripts/commit/9f4c57c0a51f6148be09ecb7b643afa0b22fceff
